name: template
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.3
  get_it: ^8.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  dio: ^5.8.0+1
  calendar_view: ^1.4.0
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  formz: ^0.8.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.3.0
  fpdart: ^1.1.0
  cloud_functions: ^6.0.5
  http: ^1.6.0
  firebase_remote_config: ^6.1.2
  package_info_plus: ^8.0.0
  store_redirect: ^2.0.1
  firebase_crashlytics: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Zilla Slab
      fonts:
        - asset: fonts/ZillaSlab-SemiBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
